@startuml
autonumber
skinparam {
Maxmessagesize 170
Roundcorner 15
ParticipantPadding 30
BoxPadding 10
DatabaseBackgroundColor Wheat
ActorFontSize 15
}


header Easy Realty
title Рассчитать ипотеку


Actor "Пользователь" as u order 10
box #MistyRose
Participant "Клиент" as c order 20
end box
box Сервер #Silver
Participant "API-Gateway" as api order 30
Participant "Ипотека" as s order 40
Participant "Адаптер" as ad order 50
Participant "User service" as us order 30
end box
box Внешняя система #BurlyWood
Participant "SRAVNI.RU" as sr order 70
end box


u -> c: Ввести данные для авторизации
c -> api: Пройти проверку данных для авторизации
api -> c: Подтвердить данные
c -> c: Отобразить главную страницу
u -> c: Открыть личный кабинет
c -> us: Передать запрос
us -> c: Отправить данные
c -> c: Отобразить доступные функции личного кабинета
u -> c: Рассчитать Ипотеку
c -> s: Передать запрос на расчет ипотеки
s -> c: Отправить данные
c -> c: Отобразить пользователю поля для заполнения
u -> c: Заполняет данные для расчета ипотеки
c -> s: Передать данные 
s -> ad: Запрос на передачу данных во внешнюю систему
ad -> sr: Передать данные для рассчета ипотеки
sr -> s: Вернуть данные
s -> c: Отправить данные
c -> c: Отобразить расчет по ипотеке пользователю 


@enduml